import type { PackRegistryEntry } from "./types";

export const builtInPacks: PackRegistryEntry[] = [
  {
    enabledByDefault: true,
    manifest: {
      id: "engineering",
      displayName: "Engineering Pack",
      zhName: "packEngineeringName",
      tagline: "packEngineeringTagline",
      description: "Inspect CAD metadata, layers, blocks, entities, model files, and drawing review signals without claiming native CAD fidelity.",
      status: "experimental",
      version: "0.1.0",
      supportedCategories: ["dwg", "model3d", "pdf", "archive"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions", "external-open"],
      keywords: ["dwg", "dxf", "cad", "step", "iges", "stl", "drawing", "工程", "图纸", "模型"],
    },
  },
  {
    enabledByDefault: true,
    manifest: {
      id: "metal-materials",
      displayName: "Metal Materials Pack",
      zhName: "packMetalMaterialsName",
      tagline: "packMetalMaterialsTagline",
      description: "Extract material grades, specifications, standards, quantities, and quotation fields from mixed business and engineering files.",
      status: "experimental",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "text", "data", "dwg", "model3d", "archive", "image"],
      permissions: ["read-file-metadata", "read-file-content", "read-workspace-summary", "suggest-actions"],
      keywords: ["steel", "metal", "stainless", "grade", "standard", "quotation", "材料", "金属", "不锈钢", "牌号", "标准", "报价"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "finance",
      displayName: "Finance Pack",
      zhName: "packFinanceName",
      tagline: "packFinanceTagline",
      description: "Identify invoices, statements, amounts, dates, currencies, and table sanity signals.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "data", "image"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["invoice", "statement", "amount", "currency", "finance", "发票", "对账", "金额", "币种"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "legal",
      displayName: "Legal Pack",
      zhName: "packLegalName",
      tagline: "packLegalTagline",
      description: "Extract parties, obligations, dates, termination clauses, and review checklist signals from legal documents.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "text", "data"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["contract", "agreement", "clause", "party", "obligation", "合同", "协议", "条款", "义务", "当事人"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "research",
      displayName: "Research Pack",
      zhName: "packResearchName",
      tagline: "packResearchTagline",
      description: "Pull authors, abstracts, figures, citations, and method keywords from research artifacts.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "text", "office"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["paper", "abstract", "author", "citation", "method", "论文", "摘要", "作者", "引用", "方法"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "developer",
      displayName: "Developer Pack",
      zhName: "packDeveloperName",
      tagline: "packDeveloperTagline",
      description: "Surface function names, modules, call paths, error stacks, and code review signals across code, JSON, and config files.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["text", "data", "archive"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["code", "function", "module", "stack", "review", "代码", "函数", "模块", "堆栈", "评审"],
    },
  },
];