import type { PackRegistryEntry } from "./types";

export const builtInPacks: PackRegistryEntry[] = [
  {
    enabledByDefault: true,
    manifest: {
      id: "engineering",
      displayName: "Engineering Pack",
      zhName: "工程包",
      tagline: "图纸、模型与工程文件的结构化检查。",
      description: "Inspect CAD metadata, layers, blocks, entities, model files, and drawing review signals without claiming native CAD fidelity.",
      status: "experimental",
      version: "0.1.0",
      supportedCategories: ["dwg", "model3d", "pdf", "archive"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions", "external-open"],
      keywords: ["dwg", "dxf", "cad", "step", "iges", "stl", "drawing", "工程", "图纸", "模型"],
    },
  },
  {
    enabledByDefault: true,
    manifest: {
      id: "metal-materials",
      displayName: "Metal Materials Pack",
      zhName: "金石包",
      tagline: "材料牌号、规格、标准与报价字段识别。",
      description: "Extract material grades, specifications, standards, quantities, and quotation fields from mixed business and engineering files.",
      status: "experimental",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "text", "data", "dwg", "model3d", "archive", "image"],
      permissions: ["read-file-metadata", "read-file-content", "read-workspace-summary", "suggest-actions"],
      keywords: ["steel", "metal", "stainless", "grade", "standard", "quotation", "材料", "金属", "不锈钢", "牌号", "标准", "报价"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "finance",
      displayName: "Finance Pack",
      zhName: "账册包",
      tagline: "票据、对账单、金额与日期识别。",
      description: "Identify invoices, statements, amounts, dates, currencies, and table sanity signals.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "data", "image"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["invoice", "statement", "amount", "currency", "finance", "发票", "对账", "金额", "币种"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "legal",
      displayName: "Legal Pack",
      zhName: "契约包",
      tagline: "合同主体、义务、期限与风险清单。",
      description: "Extract parties, obligations, dates, termination clauses, and review checklist signals from legal documents.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "office", "text"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions", "ai-assisted"],
      keywords: ["contract", "agreement", "clause", "deadline", "legal", "合同", "协议", "条款", "期限"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "research",
      displayName: "Research Pack",
      zhName: "典籍包",
      tagline: "论文、笔记、引用与阅读摘要。",
      description: "Summarize papers, notes, citations, and reading evidence for research workflows.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["pdf", "epub", "text", "office"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions", "ai-assisted"],
      keywords: ["paper", "citation", "research", "note", "阅读", "论文", "引用", "笔记"],
    },
  },
  {
    enabledByDefault: false,
    manifest: {
      id: "developer",
      displayName: "Developer Pack",
      zhName: "匠作包",
      tagline: "代码树、依赖、脚本与配置摘要。",
      description: "Inspect source trees, dependencies, scripts, project metadata, and configuration hints.",
      status: "planned",
      version: "0.1.0",
      supportedCategories: ["code", "text", "archive"],
      permissions: ["read-file-metadata", "read-file-content", "suggest-actions"],
      keywords: ["code", "package", "dependency", "script", "config", "代码", "依赖", "脚本", "配置"],
    },
  },
];
