import type { FileFormatDefinition } from "./types";

const text = ["detect", "preview", "edit", "metadata", "ai-summary", "external-open"] as const;
const route = ["detect", "metadata", "ai-summary", "external-open"] as const;
const binary = ["detect", "metadata", "external-open"] as const;

export const EXPANDED_FILE_FORMATS: FileFormatDefinition[] = [
  { extension: ".tar.gz", name: "Gzip Tarball", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compound archive; safe extraction is not implemented." },
  { extension: ".tar.bz2", name: "Bzip2 Tarball", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compound archive; safe extraction is not implemented." },
  { extension: ".tbz2", name: "Bzip2 Tarball", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compound archive; safe extraction is not implemented." },
  { extension: ".tar.xz", name: "XZ Tarball", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compound archive; safe extraction is not implemented." },
  { extension: ".txz", name: "XZ Tarball", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compound archive; safe extraction is not implemented." },
  { extension: ".zst", name: "Zstandard Archive", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized compressed file; decompression is not implemented." },
  { extension: ".jar", name: "Java Archive", category: "package", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never executes Java archives." },
  { extension: ".war", name: "Java Web Archive", category: "package", capabilities: [...binary], supportLevel: "E", boundary: "Recognized deployable package; OpenMe never executes or deploys it." },
  { extension: ".ear", name: "Java Enterprise Archive", category: "package", capabilities: [...binary], supportLevel: "E", boundary: "Recognized deployable package; OpenMe never executes or deploys it." },

  { extension: ".dng", name: "Digital Negative RAW", category: "image", capabilities: [...route], supportLevel: "D", boundary: "Recognized camera RAW file; RAW decoding is not implemented." },
  { extension: ".rw2", name: "Panasonic RAW", category: "image", capabilities: [...route], supportLevel: "D", boundary: "Recognized camera RAW file; RAW decoding is not implemented." },
  { extension: ".orf", name: "Olympus RAW", category: "image", capabilities: [...route], supportLevel: "D", boundary: "Recognized camera RAW file; RAW decoding is not implemented." },
  { extension: ".raf", name: "Fujifilm RAW", category: "image", capabilities: [...route], supportLevel: "D", boundary: "Recognized camera RAW file; RAW decoding is not implemented." },
  { extension: ".exr", name: "OpenEXR Image", category: "image", capabilities: [...binary], supportLevel: "D", boundary: "Recognized high-dynamic-range image; preview is not implemented." },
  { extension: ".hdr", name: "Radiance HDR", category: "image", capabilities: [...binary], supportLevel: "D", boundary: "Recognized HDR image; preview is not implemented." },

  { extension: ".oga", name: "Ogg Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized audio container; playback depends on runtime codec support." },
  { extension: ".weba", name: "WebM Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized audio container; playback depends on runtime codec support." },
  { extension: ".aiff", name: "AIFF Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized audio file; playback depends on runtime codec support." },
  { extension: ".aif", name: "AIFF Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized audio file; playback depends on runtime codec support." },
  { extension: ".alac", name: "Apple Lossless Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized audio file; playback depends on runtime codec support." },
  { extension: ".amr", name: "AMR Audio", category: "audio", capabilities: [...route], supportLevel: "D", boundary: "Recognized telephony audio; playback is not guaranteed." },
  { extension: ".m2ts", name: "M2TS Video", category: "video", capabilities: [...route], supportLevel: "D", boundary: "Recognized video container; codec support is not guaranteed." },
  { extension: ".mts", name: "AVCHD Video", category: "video", capabilities: [...route], supportLevel: "D", boundary: "Recognized video container; codec support is not guaranteed." },
  { extension: ".mpeg", name: "MPEG Video", category: "video", capabilities: [...route], supportLevel: "D", boundary: "Recognized video container; codec support is not guaranteed." },
  { extension: ".mpg", name: "MPEG Video", category: "video", capabilities: [...route], supportLevel: "D", boundary: "Recognized video container; codec support is not guaranteed." },
  { extension: ".mxf", name: "Material Exchange Format", category: "video", capabilities: [...route], supportLevel: "D", boundary: "Recognized professional video container; codec support is not guaranteed." },

  { extension: ".3ds", name: "3D Studio Model", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized 3D model; native parsing is not implemented." },
  { extension: ".ply", name: "Polygon File Format", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized mesh file; full material support is not implemented." },
  { extension: ".prt", name: "CAD Part", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD part; vendor-specific parsing is not implemented." },
  { extension: ".asm", name: "CAD Assembly", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD assembly; vendor-specific parsing is not implemented." },
  { extension: ".slddrw", name: "SolidWorks Drawing", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD drawing; native rendering is not implemented." },
  { extension: ".catdrawing", name: "CATIA Drawing", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD drawing; native rendering is not implemented." },
  { extension: ".ipt", name: "Inventor Part", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".iam", name: "Inventor Assembly", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".idw", name: "Inventor Drawing", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD drawing; native rendering is not implemented." },
  { extension: ".f3d", name: "Fusion 360 Design", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized CAD source; cloud/native parsing is not implemented." },
  { extension: ".3dm", name: "Rhino 3D Model", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized 3D model; native parsing is not implemented." },
  { extension: ".pln", name: "Archicad Project", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized BIM source; native parsing is not implemented." },
  { extension: ".nwd", name: "Navisworks Document", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized BIM coordination file; native parsing is not implemented." },
  { extension: ".nwc", name: "Navisworks Cache", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized BIM coordination file; native parsing is not implemented." },
  { extension: ".nwf", name: "Navisworks File Set", category: "cad", capabilities: [...route], supportLevel: "D", boundary: "Recognized BIM coordination file; native parsing is not implemented." },

  { extension: ".kicad_sch", name: "KiCad Schematic", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized EDA schematic; rendering is not implemented." },
  { extension: ".kicad_pro", name: "KiCad Project", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized EDA project; rendering is not implemented." },
  { extension: ".pcbdoc", name: "Altium PCB", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized PCB design file; native parsing is not implemented." },
  { extension: ".schdoc", name: "Altium Schematic", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized schematic file; native parsing is not implemented." },
  { extension: ".drl", name: "Excellon Drill", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized PCB drill file; manufacturing validation is not implemented." },
  { extension: ".gbl", name: "Gerber Bottom Layer", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },
  { extension: ".gtl", name: "Gerber Top Layer", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },
  { extension: ".gto", name: "Gerber Top Overlay", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },
  { extension: ".gbo", name: "Gerber Bottom Overlay", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },
  { extension: ".gts", name: "Gerber Top Soldermask", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },
  { extension: ".gbs", name: "Gerber Bottom Soldermask", category: "dwg", capabilities: [...route], supportLevel: "D", boundary: "Recognized Gerber layer; rendering is not implemented." },

  { extension: ".dbf", name: "dBASE / Shapefile Table", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized tabular/GIS companion file; table browsing is not implemented." },
  { extension: ".shx", name: "Shapefile Index", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized GIS companion file; map rendering is not implemented." },
  { extension: ".prj", name: "Projection Definition", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; CRS validation is not implemented." },
  { extension: ".geotiff", name: "GeoTIFF", category: "image", capabilities: [...route], supportLevel: "D", boundary: "Recognized geospatial raster; map rendering is not implemented." },
  { extension: ".asc", name: "ASCII Grid", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; raster visualization is not implemented." },
  { extension: ".dem", name: "Digital Elevation Model", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized terrain data; visualization is not implemented." },
  { extension: ".las", name: "LAS Point Cloud", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized point cloud file; visualization is not implemented." },
  { extension: ".laz", name: "LAZ Point Cloud", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized compressed point cloud; visualization is not implemented." },

  { extension: ".frm", name: "MySQL Table Definition", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized database file; database recovery is not implemented." },
  { extension: ".ibd", name: "InnoDB Tablespace", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized database file; database recovery is not implemented." },
  { extension: ".bak", name: "Backup File", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized backup file; restore/import is not performed." },
  { extension: ".hdf", name: "HDF", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".cdf", name: "Common Data Format", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".grib", name: "GRIB Weather Data", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized meteorological data; visualization is not implemented." },
  { extension: ".grb", name: "GRIB Weather Data", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized meteorological data; visualization is not implemented." },
  { extension: ".nii.gz", name: "Compressed NIfTI", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized medical/scientific data file; internal browsing is not implemented." },

  { extension: ".pb", name: "TensorFlow Graph", category: "other", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".tflite", name: "TensorFlow Lite Model", category: "other", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".mlmodel", name: "Core ML Model", category: "other", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".pkl", name: "Pickle Model/Data", category: "other", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never unpickles or executes serialized objects." },
  { extension: ".joblib", name: "Joblib Model/Data", category: "other", capabilities: [...binary], supportLevel: "E", boundary: "OpenMe never executes serialized model objects." },
  { extension: ".npy", name: "NumPy Array", category: "other", capabilities: [...route], supportLevel: "D", boundary: "Recognized numerical data file; array browsing is not implemented." },
  { extension: ".npz", name: "NumPy Archive", category: "archive", capabilities: [...route], supportLevel: "D", boundary: "Recognized numerical archive; array browsing is not implemented." },

  { extension: ".fa", name: "FASTA", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".fna", name: "FASTA Nucleotide", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".faa", name: "FASTA Amino Acid", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".fq", name: "FASTQ", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".cram", name: "CRAM", category: "other", capabilities: [...binary], supportLevel: "D", boundary: "Recognized bioinformatics binary; internal browsing is not implemented." },
  { extension: ".bed", name: "BED Genomic Intervals", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; genomic analysis is not implemented." },
  { extension: ".gff", name: "GFF Genome Annotation", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; genomic analysis is not implemented." },
  { extension: ".gtf", name: "GTF Genome Annotation", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; genomic analysis is not implemented." },

  { extension: ".vhdl", name: "VHDL", category: "code", capabilities: [...text], supportLevel: "A", boundary: "Text editing only; HDL is not simulated." },
  { extension: ".sdc", name: "Synopsys Design Constraints", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; timing analysis is not implemented." },
  { extension: ".sdf", name: "Standard Delay Format", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; timing simulation is not implemented." },
  { extension: ".spef", name: "Standard Parasitic Exchange Format", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; signoff analysis is not implemented." },
  { extension: ".sp", name: "SPICE Netlist", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; circuit simulation is not implemented." },
  { extension: ".spice", name: "SPICE Netlist", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; circuit simulation is not implemented." },
  { extension: ".cdl", name: "Circuit Description Language", category: "code", capabilities: [...text], supportLevel: "C", boundary: "Text preview only; circuit validation is not implemented." },
  { extension: ".dockerignore", name: "Docker Ignore", category: "code", capabilities: [...text], supportLevel: "A", boundary: "Text editing only; Docker builds are never executed." }
];
