import type { FileFormatDefinition } from "./types";

const textCapabilities = ["detect", "preview", "edit", "metadata", "ai-summary", "external-open"] as const;
const routeCapabilities = ["detect", "metadata", "ai-summary", "external-open"] as const;
const binaryRouteCapabilities = ["detect", "metadata", "external-open"] as const;

export const FILE_FORMATS: FileFormatDefinition[] = [
  { extension: ".txt", name: "Plain Text", category: "code", mime: "text/plain", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text preview and editing only; encoding detection is limited." },
  { extension: ".log", name: "Log File", category: "code", mime: "text/plain", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text preview only; large log virtualization is still limited." },
  { extension: ".ini", name: "INI Config", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Safe text editing; no schema validation." },
  { extension: ".cfg", name: "Config File", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Safe text editing; no schema validation." },
  { extension: ".conf", name: "Configuration File", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Safe text editing; no schema validation." },
  { extension: ".inf", name: "Driver INF", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text preview only; OpenMe does not install drivers." },
  { extension: ".md", name: "Markdown", category: "markdown", mime: "text/markdown", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Markdown preview and editing; embedded unsafe HTML may be sanitized by viewer behavior." },
  { extension: ".mdx", name: "MDX", category: "markdown", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Markdown-like preview; React component execution is not supported." },
  { extension: ".rtf", name: "Rich Text Format", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; rich rendering is not yet implemented." },

  { extension: ".doc", name: "Microsoft Word Legacy", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; legacy binary Office rendering is limited." },
  { extension: ".docx", name: "Microsoft Word", category: "office", capabilities: ["detect", "preview", "metadata", "ai-summary", "external-open"], supportLevel: "B", boundary: "HTML conversion preview; not source-application fidelity." },
  { extension: ".xls", name: "Microsoft Excel Legacy", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; legacy binary Excel rendering is limited." },
  { extension: ".xlsx", name: "Microsoft Excel", category: "office", capabilities: ["detect", "preview", "metadata", "ai-summary", "external-open"], supportLevel: "B", boundary: "Table preview with pagination; formulas/macros are not executed." },
  { extension: ".xlsm", name: "Excel Macro Workbook", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Macros are never executed; preview support is limited." },
  { extension: ".ppt", name: "PowerPoint Legacy", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; slide preview is not implemented." },
  { extension: ".pptx", name: "PowerPoint", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; animation and slide fidelity are not implemented." },
  { extension: ".pptm", name: "PowerPoint Macro Presentation", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Macros are never executed; preview support is limited." },
  { extension: ".wps", name: "WPS Writer", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".et", name: "WPS Spreadsheets", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".dps", name: "WPS Presentation", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".odt", name: "OpenDocument Text", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; OpenDocument rendering is not yet implemented." },
  { extension: ".ods", name: "OpenDocument Spreadsheet", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; OpenDocument rendering is not yet implemented." },
  { extension: ".odp", name: "OpenDocument Presentation", category: "office", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; OpenDocument rendering is not yet implemented." },
  { extension: ".csv", name: "CSV", category: "csv", mime: "text/csv", capabilities: ["detect", "preview", "edit", "metadata", "ai-summary", "external-open"], supportLevel: "A", boundary: "Delimited table preview; dialect detection may need refinement." },
  { extension: ".tsv", name: "TSV", category: "csv", capabilities: ["detect", "preview", "edit", "metadata", "ai-summary", "external-open"], supportLevel: "B", boundary: "Delimited table preview; treated as tabular text." },
  { extension: ".pdf", name: "PDF", category: "pdf", mime: "application/pdf", capabilities: ["detect", "preview", "metadata", "thumbnail", "ai-summary", "external-open"], supportLevel: "A", boundary: "High-quality PDF preview; editing is not supported." },
  { extension: ".djvu", name: "DjVu", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".epub", name: "EPUB", category: "epub", mime: "application/epub+zip", capabilities: ["detect", "preview", "metadata", "ai-summary", "external-open"], supportLevel: "B", boundary: "Readable book extraction; DRM and advanced layout are not supported." },
  { extension: ".mobi", name: "Mobipocket", category: "epub", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "Recognized and routed; native parsing is not implemented." },
  { extension: ".azw", name: "Kindle AZW", category: "epub", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "Recognized and routed; DRM is not bypassed." },
  { extension: ".azw3", name: "Kindle AZW3", category: "epub", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "Recognized and routed; DRM is not bypassed." },
  { extension: ".chm", name: "Compiled HTML Help", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".hlp", name: "Windows Help", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "External open route only." },

  { extension: ".jpg", name: "JPEG Image", category: "image", mime: "image/jpeg", capabilities: ["detect", "preview", "metadata", "thumbnail", "ai-summary", "external-open"], supportLevel: "A", boundary: "Browser-backed image preview; EXIF extraction is limited." },
  { extension: ".jpeg", name: "JPEG Image", category: "image", mime: "image/jpeg", capabilities: ["detect", "preview", "metadata", "thumbnail", "ai-summary", "external-open"], supportLevel: "A", boundary: "Browser-backed image preview; EXIF extraction is limited." },
  { extension: ".png", name: "PNG Image", category: "image", mime: "image/png", capabilities: ["detect", "preview", "metadata", "thumbnail", "ai-summary", "external-open"], supportLevel: "A", boundary: "Browser-backed image preview." },
  { extension: ".gif", name: "GIF Image", category: "image", mime: "image/gif", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "A", boundary: "Animated GIF depends on browser image support." },
  { extension: ".bmp", name: "Bitmap Image", category: "image", mime: "image/bmp", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "B", boundary: "Browser-backed preview." },
  { extension: ".webp", name: "WebP Image", category: "image", mime: "image/webp", capabilities: ["detect", "preview", "metadata", "thumbnail", "ai-summary", "external-open"], supportLevel: "A", boundary: "Browser-backed preview." },
  { extension: ".avif", name: "AVIF Image", category: "image", mime: "image/avif", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "B", boundary: "Preview depends on runtime codec support." },
  { extension: ".tif", name: "TIFF Image", category: "image", capabilities: ["detect", "metadata", "external-open"], supportLevel: "D", boundary: "Recognized; multi-page TIFF preview is not guaranteed." },
  { extension: ".tiff", name: "TIFF Image", category: "image", capabilities: ["detect", "metadata", "external-open"], supportLevel: "D", boundary: "Recognized; multi-page TIFF preview is not guaranteed." },
  { extension: ".heic", name: "HEIC Image", category: "image", capabilities: ["detect", "metadata", "external-open"], supportLevel: "D", boundary: "Preview depends on OS/runtime support." },
  { extension: ".heif", name: "HEIF Image", category: "image", capabilities: ["detect", "metadata", "external-open"], supportLevel: "D", boundary: "Preview depends on OS/runtime support." },
  { extension: ".raw", name: "Camera RAW", category: "image", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized as RAW-like image; vendor decoding is not implemented." },
  { extension: ".cr2", name: "Canon RAW", category: "image", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "RAW decoding is not implemented." },
  { extension: ".nef", name: "Nikon RAW", category: "image", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "RAW decoding is not implemented." },
  { extension: ".arw", name: "Sony RAW", category: "image", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "RAW decoding is not implemented." },
  { extension: ".ico", name: "Windows Icon", category: "image", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "B", boundary: "Basic image preview; multi-resolution details may be limited." },
  { extension: ".icns", name: "Apple Icon", category: "image", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; ICNS parsing is not implemented." },
  { extension: ".svg", name: "SVG", category: "svg", mime: "image/svg+xml", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "B", boundary: "Rendered safely as image; script execution is not supported." },
  { extension: ".psd", name: "Photoshop Document", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized design source; Photoshop fidelity and editing are not supported." },
  { extension: ".psb", name: "Photoshop Large Document", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized design source; Photoshop fidelity and editing are not supported." },
  { extension: ".ai", name: "Adobe Illustrator", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized design source; Illustrator fidelity is not supported." },
  { extension: ".eps", name: "Encapsulated PostScript", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized print/vector format; rendering is not guaranteed." },
  { extension: ".cdr", name: "CorelDRAW", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route; native parsing is not implemented." },
  { extension: ".sketch", name: "Sketch", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized design source; native parsing is not implemented." },
  { extension: ".fig", name: "Figma", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized design source; online Figma parsing is not implemented." },
  { extension: ".xd", name: "Adobe XD", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized prototype source; native parsing is not implemented." },

  { extension: ".mp3", name: "MP3 Audio", category: "audio", mime: "audio/mpeg", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Playback depends on runtime codec support." },
  { extension: ".wav", name: "WAV Audio", category: "audio", mime: "audio/wav", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Playback depends on runtime codec support." },
  { extension: ".flac", name: "FLAC Audio", category: "audio", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on runtime codec support." },
  { extension: ".ape", name: "APE Audio", category: "audio", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".aac", name: "AAC Audio", category: "audio", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on runtime codec support." },
  { extension: ".ogg", name: "Ogg Audio", category: "audio", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on runtime codec support." },
  { extension: ".opus", name: "Opus Audio", category: "audio", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on runtime codec support." },
  { extension: ".m4a", name: "M4A Audio", category: "audio", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on runtime codec support." },
  { extension: ".wma", name: "Windows Media Audio", category: "audio", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".mid", name: "MIDI", category: "audio", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; MIDI synthesis is not implemented." },
  { extension: ".midi", name: "MIDI", category: "audio", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; MIDI synthesis is not implemented." },
  { extension: ".mp4", name: "MP4 Video", category: "video", mime: "video/mp4", capabilities: ["detect", "preview", "metadata", "thumbnail", "external-open"], supportLevel: "B", boundary: "Playback depends on codec support." },
  { extension: ".mov", name: "QuickTime Video", category: "video", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on codec support." },
  { extension: ".avi", name: "AVI Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".mkv", name: "Matroska Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".webm", name: "WebM Video", category: "video", mime: "video/webm", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Playback depends on codec support." },
  { extension: ".flv", name: "Flash Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized legacy format; playback is not guaranteed." },
  { extension: ".f4v", name: "Flash MP4 Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized legacy format; playback is not guaranteed." },
  { extension: ".rm", name: "RealMedia", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".rmvb", name: "RealMedia Variable Bitrate", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".wmv", name: "Windows Media Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".ts", name: "MPEG Transport Stream", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".m4v", name: "M4V Video", category: "video", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Playback depends on codec support." },
  { extension: ".3gp", name: "3GP Video", category: "video", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized; playback is not guaranteed." },
  { extension: ".prproj", name: "Premiere Pro Project", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized media project; source application fidelity is not supported." },
  { extension: ".aep", name: "After Effects Project", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized media project; source application fidelity is not supported." },
  { extension: ".aup3", name: "Audacity Project", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized audio project; source application fidelity is not supported." },
  { extension: ".veg", name: "Vegas Project", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized video project; source application fidelity is not supported." },
  { extension: ".fcpxml", name: "Final Cut Pro XML", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "XML text view; Final Cut timeline fidelity is not implemented." },
  { extension: ".drp", name: "DaVinci Resolve Project", category: "design", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized video project; source application fidelity is not supported." },

  { extension: ".py", name: "Python", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".js", name: "JavaScript", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".mjs", name: "JavaScript Module", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".cjs", name: "CommonJS", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".ts", name: "TypeScript", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".java", name: "Java", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".go", name: "Go", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".c", name: "C", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".cpp", name: "C++", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".h", name: "C/C++ Header", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".hpp", name: "C++ Header", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".cs", name: "C#", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".php", name: "PHP", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".rb", name: "Ruby", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".swift", name: "Swift", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".kt", name: "Kotlin", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".rs", name: "Rust", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".scala", name: "Scala", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".lua", name: "Lua", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".pl", name: "Perl", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".r", name: "R", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code is never executed." },
  { extension: ".html", name: "HTML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; HTML is not executed as an app." },
  { extension: ".htm", name: "HTML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; HTML is not executed as an app." },
  { extension: ".css", name: "CSS", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only." },
  { extension: ".scss", name: "SCSS", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only." },
  { extension: ".less", name: "Less", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only." },
  { extension: ".sass", name: "Sass", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only." },
  { extension: ".vue", name: "Vue Component", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; component is not executed." },
  { extension: ".jsx", name: "React JSX", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; component is not executed." },
  { extension: ".tsx", name: "React TSX", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; component is not executed." },
  { extension: ".svelte", name: "Svelte Component", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; component is not executed." },
  { extension: ".json", name: "JSON", category: "json", mime: "application/json", capabilities: [...textCapabilities], supportLevel: "A", boundary: "JSON preview/edit; schema validation is not automatic." },
  { extension: ".jsonl", name: "JSON Lines", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Line-based text preview; huge-file virtualization is limited." },
  { extension: ".yml", name: "YAML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".yaml", name: "YAML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".xml", name: "XML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".toml", name: "TOML", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".properties", name: "Java Properties", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".env", name: "Environment File", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text editing only; secrets are not masked yet." },
  { extension: ".gitignore", name: "Git Ignore", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text editing only." },
  { extension: ".dockerfile", name: "Dockerfile", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; Docker build is never executed." },
  { extension: ".sql", name: "SQL", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; SQL is not executed." },
  { extension: ".sh", name: "Shell Script", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; scripts are never executed." },
  { extension: ".bat", name: "Windows Batch", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; scripts are never executed." },
  { extension: ".cmd", name: "Windows Command Script", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; scripts are never executed." },
  { extension: ".ps1", name: "PowerShell", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; scripts are never executed." },
  { extension: ".vbs", name: "VBScript", category: "code", capabilities: [...textCapabilities], supportLevel: "B", boundary: "Text editing only; scripts are never executed." },
  { extension: ".proto", name: "Protocol Buffers", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; code generation is not executed." },
  { extension: ".graphql", name: "GraphQL", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".gql", name: "GraphQL", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; schema validation is not automatic." },
  { extension: ".tf", name: "Terraform", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; Terraform is never executed." },
  { extension: ".tfvars", name: "Terraform Variables", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; Terraform is never executed." },
  { extension: ".gradle", name: "Gradle", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; build scripts are never executed." },

  { extension: ".zip", name: "ZIP Archive", category: "archive", mime: "application/zip", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "ZIP listing and safe extraction; non-ZIP archives need external tools." },
  { extension: ".rar", name: "RAR Archive", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in RAR extraction is not implemented." },
  { extension: ".7z", name: "7-Zip Archive", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in 7z extraction is not implemented." },
  { extension: ".tar", name: "TAR Archive", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in TAR extraction is not implemented." },
  { extension: ".gz", name: "Gzip", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in gzip extraction is not implemented." },
  { extension: ".tgz", name: "Tar Gzip", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in extraction is not implemented." },
  { extension: ".bz2", name: "Bzip2", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in extraction is not implemented." },
  { extension: ".xz", name: "XZ", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized and routed; built-in extraction is not implemented." },
  { extension: ".cab", name: "Windows Cabinet", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },

  { extension: ".exe", name: "Windows Executable", category: "package", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes installers or unknown binaries." },
  { extension: ".msi", name: "Windows Installer", category: "package", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes installers." },
  { extension: ".msix", name: "MSIX Package", category: "package", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never installs packages." },
  { extension: ".dmg", name: "macOS Disk Image", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts disk images automatically." },
  { extension: ".pkg", name: "macOS Installer", category: "package", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never runs installers." },
  { extension: ".apk", name: "Android APK", category: "package", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized Android package; OpenMe does not install or run it." },
  { extension: ".aab", name: "Android App Bundle", category: "package", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized Android bundle; OpenMe does not install or run it." },
  { extension: ".ipa", name: "iOS App", category: "package", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized iOS package; OpenMe does not install or run it." },
  { extension: ".deb", name: "Debian Package", category: "package", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized Linux package; OpenMe does not install it." },
  { extension: ".rpm", name: "RPM Package", category: "package", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized Linux package; OpenMe does not install it." },
  { extension: ".appimage", name: "AppImage", category: "package", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes AppImage binaries." },
  { extension: ".iso", name: "ISO Image", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts images automatically." },
  { extension: ".img", name: "Disk Image", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts images automatically." },
  { extension: ".wim", name: "Windows Imaging Format", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "Recognized system image; OpenMe does not deploy images." },
  { extension: ".gho", name: "Ghost Image", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "Recognized backup image; OpenMe does not restore images." },

  { extension: ".obj", name: "Wavefront OBJ", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "3D preview is approximate; materials may be limited." },
  { extension: ".fbx", name: "FBX", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized 3D format; full animation/material fidelity is not implemented." },
  { extension: ".stl", name: "STL", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Mesh preview only; manufacturing validation is not performed." },
  { extension: ".3mf", name: "3D Manufacturing Format", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "3D manufacturing preview is approximate; no print validation is performed." },
  { extension: ".blend", name: "Blender", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized source project; Blender fidelity is not implemented." },
  { extension: ".max", name: "3ds Max", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".ma", name: "Maya ASCII", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; Maya scene fidelity is not implemented." },
  { extension: ".mb", name: "Maya Binary", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".c4d", name: "Cinema 4D", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".dae", name: "COLLADA", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized 3D exchange file; preview may be limited." },
  { extension: ".gltf", name: "glTF", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "3D preview is approximate." },
  { extension: ".glb", name: "Binary glTF", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "3D preview is approximate." },
  { extension: ".iges", name: "IGES", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Industrial CAD preview is approximate." },
  { extension: ".igs", name: "IGES", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Industrial CAD preview is approximate." },
  { extension: ".step", name: "STEP", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Industrial CAD preview is approximate; no manufacturing guarantee." },
  { extension: ".stp", name: "STEP", category: "cad", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "C", boundary: "Industrial CAD preview is approximate; no manufacturing guarantee." },
  { extension: ".dwg", name: "AutoCAD DWG", category: "dwg", capabilities: ["detect", "metadata", "ai-summary", "external-open"], supportLevel: "D", boundary: "Semantic inspection and compatible preview only; not AutoCAD fidelity." },
  { extension: ".dxf", name: "AutoCAD DXF", category: "dwg", capabilities: ["detect", "metadata", "ai-summary", "external-open"], supportLevel: "D", boundary: "Semantic inspection and compatible preview only; not AutoCAD fidelity." },
  { extension: ".dgn", name: "MicroStation DGN", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized engineering drawing; native parsing is not implemented." },
  { extension: ".skp", name: "SketchUp", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized 3D design file; native parsing is not implemented." },
  { extension: ".rvt", name: "Revit Project", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized BIM source; native parsing is not implemented." },
  { extension: ".rfa", name: "Revit Family", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized BIM source; native parsing is not implemented." },
  { extension: ".ifc", name: "Industry Foundation Classes", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized BIM exchange file; full BIM inspection is not implemented." },
  { extension: ".sat", name: "ACIS SAT", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD exchange file; native parsing is not implemented." },
  { extension: ".x_t", name: "Parasolid Text", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD exchange file; native parsing is not implemented." },
  { extension: ".x_b", name: "Parasolid Binary", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD exchange file; native parsing is not implemented." },
  { extension: ".sldprt", name: "SolidWorks Part", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".sldasm", name: "SolidWorks Assembly", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".catpart", name: "CATIA Part", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".catproduct", name: "CATIA Product", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized CAD source; native parsing is not implemented." },
  { extension: ".jt", name: "JT", category: "cad", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized lightweight CAD exchange file; native parsing is not implemented." },

  { extension: ".db", name: "SQLite Database", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "D", boundary: "Recognized database file; SQL browsing is not implemented." },
  { extension: ".db3", name: "SQLite Database", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "D", boundary: "Recognized database file; SQL browsing is not implemented." },
  { extension: ".sqlite", name: "SQLite Database", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "D", boundary: "Recognized database file; SQL browsing is not implemented." },
  { extension: ".mdb", name: "Access Database", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".accdb", name: "Access Database", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "D", boundary: "External open route only." },
  { extension: ".parquet", name: "Apache Parquet", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized columnar data file; table preview is not implemented." },
  { extension: ".orc", name: "Apache ORC", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized columnar data file; table preview is not implemented." },
  { extension: ".avro", name: "Apache Avro", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized data file; preview is not implemented." },
  { extension: ".feather", name: "Feather", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized data file; preview is not implemented." },
  { extension: ".h5", name: "HDF5", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".hdf5", name: "HDF5", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".nc", name: "NetCDF", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".mat", name: "MATLAB Data", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized scientific data file; internal browsing is not implemented." },
  { extension: ".fits", name: "FITS", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized scientific image/data file; internal browsing is not implemented." },
  { extension: ".nii", name: "NIfTI", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized medical/scientific data file; internal browsing is not implemented." },

  { extension: ".vmdk", name: "VMware Disk", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts or boots virtual disks." },
  { extension: ".vdi", name: "VirtualBox Disk", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts or boots virtual disks." },
  { extension: ".vhd", name: "Virtual Hard Disk", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts or boots virtual disks." },
  { extension: ".vhdx", name: "Hyper-V Disk", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts or boots virtual disks." },
  { extension: ".qcow2", name: "QEMU QCOW2", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never mounts or boots virtual disks." },
  { extension: ".ova", name: "Open Virtual Appliance", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never imports or boots virtual machines." },
  { extension: ".ovf", name: "Open Virtualization Format", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never imports or boots virtual machines." },
  { extension: ".snapshot", name: "Virtual Machine Snapshot", category: "disk", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never restores VM snapshots." },

  { extension: ".ttf", name: "TrueType Font", category: "font", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Basic font preview; advanced font tables are not fully inspected." },
  { extension: ".otf", name: "OpenType Font", category: "font", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Basic font preview; advanced font tables are not fully inspected." },
  { extension: ".woff", name: "Web Font", category: "font", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Basic font preview." },
  { extension: ".woff2", name: "Web Font 2", category: "font", capabilities: ["detect", "preview", "metadata", "external-open"], supportLevel: "B", boundary: "Basic font preview." },
  { extension: ".eot", name: "Embedded OpenType", category: "font", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized legacy font; preview is not guaranteed." },
  { extension: ".ttc", name: "TrueType Collection", category: "font", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized font collection; preview is not guaranteed." },
  { extension: ".pfb", name: "PostScript Font Binary", category: "font", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized legacy font; preview is not guaranteed." },
  { extension: ".pfm", name: "PostScript Font Metrics", category: "font", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized legacy font; preview is not guaranteed." },

  { extension: ".rom", name: "Game ROM", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never emulates or runs ROM files." },
  { extension: ".pak", name: "Game Resource Pack", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized resource package; game-specific extraction is not implemented." },
  { extension: ".unitypackage", name: "Unity Package", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized package; Unity import is not performed." },
  { extension: ".uasset", name: "Unreal Asset", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized game asset; Unreal parsing is not implemented." },
  { extension: ".mcworld", name: "Minecraft World", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized archive-like world file; game import is not performed." },
  { extension: ".sav", name: "Game Save", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "External open route only." },

  { extension: ".torrent", name: "BitTorrent File", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized metadata file; OpenMe does not download torrents." },
  { extension: ".cer", name: "Certificate", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized certificate; trust validation is not implemented." },
  { extension: ".crt", name: "Certificate", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized certificate; trust validation is not implemented." },
  { extension: ".pem", name: "PEM Certificate/Key", category: "code", capabilities: [...textCapabilities], supportLevel: "D", boundary: "Text preview only; private key handling is not audited." },
  { extension: ".pfx", name: "PKCS#12 Bundle", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe does not import certificates." },
  { extension: ".p12", name: "PKCS#12 Bundle", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe does not import certificates." },
  { extension: ".key", name: "Private Key", category: "code", capabilities: [...textCapabilities], supportLevel: "D", boundary: "Text preview only; secrets are not masked yet." },
  { extension: ".ics", name: "Calendar", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; calendar UI is not implemented." },
  { extension: ".vcf", name: "vCard", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; contact UI is not implemented." },
  { extension: ".mbox", name: "Mailbox Archive", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized mail archive; mail browsing is not implemented." },
  { extension: ".eml", name: "Email Message", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized email file; MIME rendering is not implemented." },

  { extension: ".pages", name: "Apple Pages", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".numbers", name: "Apple Numbers", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".keynote", name: "Apple Keynote", category: "office", capabilities: [...routeCapabilities], supportLevel: "E", boundary: "External open route only." },
  { extension: ".kicad_pcb", name: "KiCad PCB", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized PCB file; EDA rendering is not implemented." },
  { extension: ".sch", name: "Schematic", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized schematic file; EDA rendering is not implemented." },
  { extension: ".brd", name: "Board Layout", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized board file; EDA rendering is not implemented." },
  { extension: ".gbr", name: "Gerber", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized PCB manufacturing file; rendering is not implemented." },
  { extension: ".ger", name: "Gerber", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized PCB manufacturing file; rendering is not implemented." },
  { extension: ".dsn", name: "Design File", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized EDA/design file; native parsing is not implemented." },
  { extension: ".shp", name: "ESRI Shapefile", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized GIS file; map rendering is not implemented." },
  { extension: ".geojson", name: "GeoJSON", category: "json", capabilities: [...textCapabilities], supportLevel: "B", boundary: "JSON preview; map rendering is not implemented." },
  { extension: ".gpkg", name: "GeoPackage", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized GIS package; map rendering is not implemented." },
  { extension: ".kml", name: "KML", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "XML text preview; map rendering is not implemented." },
  { extension: ".kmz", name: "KMZ", category: "archive", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized compressed GIS file; map rendering is not implemented." },
  { extension: ".onnx", name: "ONNX Model", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized AI model; model execution is not supported." },
  { extension: ".pt", name: "PyTorch Model", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".pth", name: "PyTorch Checkpoint", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".ckpt", name: "Checkpoint", category: "other", capabilities: [...binaryRouteCapabilities], supportLevel: "E", boundary: "OpenMe never executes model files." },
  { extension: ".safetensors", name: "SafeTensors", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized model tensor file; model execution is not supported." },
  { extension: ".gguf", name: "GGUF Model", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized LLM model file; model execution is not supported." },
  { extension: ".fasta", name: "FASTA", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".fastq", name: "FASTQ", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".sam", name: "SAM", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; bioinformatics analysis is not implemented." },
  { extension: ".bam", name: "BAM", category: "other", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized bioinformatics binary; internal browsing is not implemented." },
  { extension: ".gds", name: "GDSII", category: "dwg", capabilities: [...routeCapabilities], supportLevel: "D", boundary: "Recognized chip layout file; EDA rendering is not implemented." },
  { extension: ".lef", name: "LEF", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; chip-design semantics are not implemented." },
  { extension: ".def", name: "DEF", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; chip-design semantics are not implemented." },
  { extension: ".lib", name: "Liberty/Library", category: "code", capabilities: [...textCapabilities], supportLevel: "C", boundary: "Text preview only; chip-design semantics are not implemented." },
  { extension: ".v", name: "Verilog", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; HDL is not simulated." },
  { extension: ".sv", name: "SystemVerilog", category: "code", capabilities: [...textCapabilities], supportLevel: "A", boundary: "Text editing only; HDL is not simulated." }
];
